spring.security.oauth2.client:
  registration:
    kakao:
      client-authentication-method: client_secret_post
      authorization-grant-type: authorization_code
      client-secret: ${KAKAO_CLIENT_SECRET}
      client-id: ${KAKAO_CLIENT_ID}
      client-name: kakao
      scope:
        - account_email

  provider:
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: id

aes256.key: ${AES256_KEY}
jwt.secret-key: ${JWT_SECRET_KEY}

auth:
  allowed-front-end-origins:
    - http://localhost:*
    - https://localhost:*
  success-uri: /auth/success

