spring:
  application.name: capstone
  profiles.default: dev
  config:
    import:
      - classpath:config/application-security.yml
      - classpath:config/application-dev-db.yml
server:
  port: 9090
