spring.application.name: capstone

aes256.key: ${AES256_KEY}

spring.security.oauth2.client.registration:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}

auth.allowed-front-end-origins: http://localhost:*,https://localhost:*,https://st4r-starlight.vercel.app