spring:
  application.name: capstone
  profiles.default: dev
  main:
    web-application-type: servlet
  config:
    import:
      - classpath:config/application-security.yml
      - classpath:config/application-gemini.yml
      - classpath:config/application-rtzr.yml
      - classpath:config/application-prompt.yml

server:
  forward-headers-strategy: native
  port: 18080